version: "3" 
services: 
  db: 
    image: postgres 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: flask_db 
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  web: 
    build: . 
    command: sh -c "python init_db.py & python app.py"
    ports: 
      - "5000:5000" 
    depends_on: 
      - db 
    environment: 
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/flask_db
    command: python app.py 
  init-db: 
    build: .  
    depends_on: 
      - db
    environment: 
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/flask_db
    command: python init_db.py 
volumes: 
  postgres-data:
  

