version: '3'

services:
  app:
    build: .
    ports:
      - "5000:9090"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/flask_db
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  