version: '3'
services:
  app:
    build: .
    ports:
      - "5000:9090"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:1234@*:5432/flask_db
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=flask_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
