version: "3.9" 
services: 
  postgres: 
    image: postgres 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: flask_db 
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  web: 
    build: . 
    command: sh -c "python init_db.py & python app.py"
    ports: 
      - "5000:5000" 
    depends_on: 
      - postgres 
    environment: 
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/flask_db
    #command: python app.py 
volumes: 
  postgres-data:

  

