version: "1.29" 
services: 
  db: 
    image: postgres 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: flask_db 
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  web: 
    build: . 
    command: sh -c "python init_db.py & python app.py"
    ports: 
      - "5000:5000" 
    depends_on: 
      - db 
    environment: 
      DATABASE_URL: postgres://postgres:1234@db:5432/flask_db
    command: python app.py 
  init-db: 
    build: .  
    depends_on: 
      - db
    environment: 
      DATABASE_URL: postgres://postgres:1234@db:5432/flask_db 
    command: python init_db.py 
volumes: 
  postgres-data:

