apiVersion: v1
kind: Pod
metadata: 
  name: flask-db
  namespace: Web
  labels: 
    run: myapp
spec:
  Containers:
    - name: db
	    image: postgres
      environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: flask_db
      volumes: 
      - postgres-data:/var/lib/postgresql/data	  
	
	  - name: web
      image: flask-postgresql_web
      command: [ sh -c "python init_db.py & python app.py" ]
	    ports: 
      - containerPort: 5000 
      depends_on: 
      - db 
      environment: 
        DATABASE_URL: postgres://postgres:1234@db:5432/flask_db
