apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: flask-crud-k8s
          image: dina2022/dbflask:1.4
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST   # Setting database host from configmap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName

---
apiVersion: v1
kind: Service
metadata:
  name: flask-crud-deployment
spec:
  selector:
     app: myapp
  ports:
     - protocol: TCP
       port: 5000     # the port that the service is running on in the cluster
       targetPort: 5000   # the port exposed by the service
  type: NodePort
