apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: dina2022/dbflask:1.1
          ports:
            - containerPort: 5000
          env:
            - name: myapp-config
              value: app_config.json
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: database-url
      imagePullSecrets:
        - name: myregistrykey
