apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: Web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      Containers:
        - name: db
	        image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          volumes: 
          - postgres-data:/var/lib/postgresql/data	
          environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: flask_db
            
	      - name: web
          image: flask-postgresql_web
          ports: 
          - containerPort: 5000 
          command: [ sh -c "python init_db.py & python app.py" ]
          depends_on: 
          - db 
          environment: 
          DATABASE_URL: postgres://postgres:1234@db:5432/flask_db	  
