name: build flask postgreSQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERUSERNAME}}
          password: ${{ secrets.DOCKERPASS }}
          #repository: Dinahalem/flask-docker
          
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dina2022/dbflask:1.1

              
  Run_container:
    name: run container
    needs: build
    runs-on: ubuntu-latest  
    steps:    
    - name: run postgres-server
      run: docker network create flaskdb
      
    - name: Start Docker containers web
      run: |
         docker run --name my-pgadmin -p 9001:9001 -e PGADMIN_DEFAULT_EMAIL=user@domain.com -e PGADMIN_DEFAULT_PASSWORD=supersecret -d dpage/pgadmin4
         docker run --name postgres-server -e POSTGRES_PASSWORD=1234 -d -p 5432:5432 postgres
         
         docker logs postgres-server
         docker run --name my-flask-app-container -e DATABASE_URL=postgres://postgres:1234@postgres-server:5432/flask_db --link postgres-server:postgres-server -p 5000:5000 dina2022/dbflask:1.1
         
         
         
         #sudo -u postgres -i
         #psql -U postgres -c "CREATE DATABASE flask_db;"
         #docker run -p 8082:5000 -d --name web --network flaskdb dina2022/dbflask:1.1
         #docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres-server 
         #docker logs my-pgadmin
    #- name: run postgres-server
      #run: 
         
          
  
 
