name: build flask postgreSQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERUSERNAME}}
          password: ${{ secrets.DOCKERPASS }}
          #repository: Dinahalem/flask-docker
          
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dina2022/dbflask:1.1


   
      #- name: Install Docker Compose
       # run: |
        #  sudo apt-get update
         # sudo apt-get install -y docker-compose

      - name: Start Docker containers web
        run: |
          #docker-compose --version
          docker-compose --env-file .env up -d 
         
      #- name: Install kubectl
       # run: |
        #  sudo apt-get update && sudo apt-get install -y apt-transport-https
         # curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          #echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          #sudo apt-get update
          #sudo apt-get install -y kubectl
      #- name: Install Minikube
       # run: |
        #  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
         # sudo dpkg -i minikube_latest_amd64.deb
    
      - name: Set up Minikube
        uses: kubernetes-sigs/setup-minikube@v2

      - name: Set up kubectl
        uses: kubernetes-sigs/setup-kubectl@v2
        
      - name: Start kubernetes         
        run: |
          minikube start
          kubectl apply -f k8s/*
          
      - name: Test application
        run: curl http://localhost:5000
          
 
