name: build flask postgreSQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERUSERNAME}}
          password: ${{ secrets.DOCKERPASS }}
          #repository: Dinahalem/flask-docker
          
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dina2022/dbflask:1.1


      - name: Start docker-compose
        run: |
          #docker-compose --version
          #docker-compose --env-file .env up -d 
          docker-compose up --build
          docker ps 

      - name: Test application
        run: curl http://localhost:5000
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        
      - name: Start kubernetes         
        run: |
          minikube start
          kubectl apply -f K8s/secret.yaml
          kubectl apply -f K8s/configmap.yaml
          kubectl apply -f K8s/delopy.yaml
          kubectl apply -f K8s/service.yaml
        
      - name: Test service URLs
        run: |
          minikube service list
          minikube service node-port --url     
 
