name: build flask postgreSQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERUSERNAME}}
          password: ${{ secrets.DOCKERPASS }}
          #repository: Dinahalem/flask-docker
          
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dina2022/dbflask:1.1

                  
  Run_container:
    name: run container
    needs: build
    runs-on: ubuntu-latest  
    steps:         
    - name: Make docker-compose.yaml executable
      run: |
         cd flask-PostgreSQL
         chmod +x docker-compose.yaml
    
    - name: Build Docker images
      run: docker-compose build

    - name: Start Docker containers
      run: docker-compose up
          
  
 
